### PR TITLE
Facts about Anna

### PR DESCRIPTION
**Pull request by kimjoyc**
This PR adds an about page for Anna with answers to interview questions.

### CODE REVIEW

**Review by annamarieweber — COMMENTED** [review]
No specific feedback on the Changes for the file, however I am wondering do we want to try to use the same format for all of our posts and do we want to also add photos to them? We can create new issues for that work but just thought it might be nice :) 

In terms of feedback if you could add a more descriptive title to the pr that briefly describes the change you made that is something that is a good habit to get into. I don't think that we were given any specific conventions so it might be a good thing for us to establish our own set of conventions for as a team so that we have some consistency.  Additionally add a brief description of your changes to the PR description as well as tagging the related issue.

Otherwise everything looks great!

**Comment by kimjoyc** [comment]
Yeah I asked about photos. Definitely can do that. Do you wanna finish all
that tonight? I wasn’t sure how to add the photos. I’ll definitely take a
look at it tomorrow!

**Comment by kimjoyc** [comment]
> No specific feedback on the Changes for the file, however I am wondering do we want to try to use the same format for all of our posts and do we want to also add photos to them? We can create new issues for that work but just thought it might be nice :)
> 
> In terms of feedback if you could add a more descriptive title to the pr that briefly describes the change you made that is something that is a good habit to get into. I don't think that we were given any specific conventions so it might be a good thing for us to establish our own set of conventions for as a team so that we have some consistency. Additionally add a brief description of your changes to the PR description as well as tagging the related issue.
> 
> Otherwise everything looks great!

Hey, just finished editing the post. Not sure how to add photos or if that's an entirely different assignment.

**Comment by janash** [comment]
Hey @kimjoyc , I believe @annamarieweber was referring to the description and title of the pull request in her review. 

Your PRs should typically have a description of what you did in the PR in the red boxed area. The title of the PR should be descriptive of the PR as well (orange circle.) To edit the title, click the "Edit" button on the right of the title. To edit the description, click the button with three dots to the left of the description and choose "edit"

Screen Shot 2021-08-10 at 8 53 00 AM

**Comment by annamarieweber** [comment]
> > No specific feedback on the Changes for the file, however I am wondering do we want to try to use the same format for all of our posts and do we want to also add photos to them? We can create new issues for that work but just thought it might be nice :)
> > In terms of feedback if you could add a more descriptive title to the pr that briefly describes the change you made that is something that is a good habit to get into. I don't think that we were given any specific conventions so it might be a good thing for us to establish our own set of conventions for as a team so that we have some consistency. Additionally add a brief description of your changes to the PR description as well as tagging the related issue.
> > Otherwise everything looks great!
> 
> Hey, just finished editing the post. Not sure how to add photos or if that's an entirely different assignment.

No need to add photos for now! Just update the PR title and description!

**Review by annamarieweber — APPROVED** [review]
Looks good!

**Pull request merged**
